spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql

  data:
    redis:
      url: ${REDIS_URL:rediss://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}}
      lettuce:
        pool:
          enabled: true

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: https://hacker2.parkjoowon.site/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: https://hacker2.parkjoowon.site/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth:
  default-password: ${OAUTH_DEFAULT_PASSWORD}

jwt:
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer}
  secret: ${JWT_SECRET}
  access-expiration: 6048000
  refresh-expiration: 6048000