spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql

  data:
    redis:
      host: ${REDIS_HOST:redis-13768.c340.ap-northeast-2-1.ec2.redns.redis-cloud.com}
      port: ${REDIS_PORT:13768}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:true}

  jackson:
    property-naming-strategy: SNAKE_CASE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: https://hacker2.parkjoowon.site/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

oauth:
  default-password: ${OAUTH_DEFAULT_PASSWORD}

jwt:
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  secret: ${JWT_SECRET}
  access-expiration: 6048000
  refresh-expiration: 6048000

